feat(makefile): add a `Makefile` to help create `bindings` crate.
gakonst/foundry-rust-template pull request #9
Opened 2023-11-27 00:54 UTC by itsdevbear

2023-11-27 00:58 UTC, itsdevbear commented
@mattsse

2023-11-28 18:14 UTC, mattsse approved these changes
this seems fine.

lgtm

2023-11-28 18:17 UTC, mattsse requested changes
could you check the CI jobs, I think they need to be updated since we moved the bindings folder

2023-11-28 23:47 UTC, mattsse approved these changes

2023-11-28 23:56 UTC, merged